name = "quilt-modpack"
author = "BattleCh1cken"
version = "1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "146f85288c638c7c10a51051219964814493a1e52d4becb6620fb474269b434d"

[versions]
minecraft = "1.19.2"
quilt = "0.17.7"

[options]
acceptable-game-versions = ["1.19.3", "1.19.2", "1.19"]
